Neos:
  ContentRepositoryRegistry:
    presets:
      default:
        propertyConverters:
          CarbonSlideshowEditorNormalizer:
            position: "start 1000"
            className: Carbon\SlideshowEditor\Infrastructure\SlideshowNormalizer
